-- 코드를 입력하세요
SELECT
    USER_ID
    , NICKNAME
    , SUM(PRICE) TOTAL_SALES
FROM (
    SELECT
        B.USER_ID
        , B.NICKNAME
        , A.PRICE
    FROM USED_GOODS_BOARD A, USED_GOODS_USER B
    WHERE A.WRITER_ID = B.USER_ID
      AND A.STATUS = 'DONE'
)
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)