-- 코드를 입력하세요
SELECT
    TO_CHAR(DATETIME, 'FMHH24') HOUR
    , COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'FMHH24')
HAVING TO_CHAR(DATETIME, 'FMHH24') BETWEEN 9 AND 19
ORDER BY TO_NUMBER(HOUR)